"""Central configuration for the plagiarism detection engine."""

SPACY_MODEL_NAME = "en_core_web_sm"
SENTENCE_TRANSFORMER_MODEL_NAME = "all-MiniLM-L6-v2"
PERCENTAGE_MULTIPLIER = 100.0
MAX_PERCENTAGE = 100.0
ROUNDING_PRECISION = 2
SENTENCE_MATCH_THRESHOLD = 68.0

EXACT_COPY_SEMANTIC_THRESHOLD = 92.0
EXACT_COPY_RAPIDFUZZ_THRESHOLD = 88.0
EXACT_COPY_COVERAGE_THRESHOLD = 70.0
NEAR_COPY_SEMANTIC_THRESHOLD = 82.0
NEAR_COPY_RAPIDFUZZ_THRESHOLD = 65.0
NEAR_COPY_COVERAGE_THRESHOLD = 45.0
NEAR_COPY_AVERAGE_SENTENCE_THRESHOLD = 75.0
HEAVY_PARAPHRASING_SEMANTIC_THRESHOLD = 70.0
HEAVY_PARAPHRASING_RAPIDFUZZ_THRESHOLD = 70.0
HEAVY_PARAPHRASING_TFIDF_THRESHOLD = 55.0
HEAVY_PARAPHRASING_COVERAGE_THRESHOLD = 40.0
HEAVY_PARAPHRASING_MATCH_COUNT = 2
HEAVY_PARAPHRASING_AVERAGE_SENTENCE_THRESHOLD = 70.0
HEAVY_PARAPHRASING_STRONG_SENTENCE_PERCENTAGE = 4.0
POSSIBLE_PARAPHRASING_SEMANTIC_THRESHOLD = 60.0
POSSIBLE_PARAPHRASING_HIGHEST_SENTENCE_THRESHOLD = 75.0
POSSIBLE_PARAPHRASING_MATCH_COUNT = 1
MIXED_HIGH_RISK_THRESHOLD = 85.0
MIXED_MODERATE_RISK_THRESHOLD = 70.0
MIXED_LOW_RISK_THRESHOLD = 45.0

SEMANTIC_WEIGHT = 0.45
LEXICAL_WEIGHT = 0.20
COVERAGE_WEIGHT = 0.15
SENTENCE_EVIDENCE_WEIGHT = 0.20
ALGORITHM_AGREEMENT_WEIGHT = 0.45
SEMANTIC_EVIDENCE_WEIGHT = 0.30
SENTENCE_SUPPORT_WEIGHT = 0.25
SENTENCE_SUPPORT_COVERAGE_WEIGHT = 0.45
SENTENCE_SUPPORT_AVERAGE_WEIGHT = 0.35
SENTENCE_SUPPORT_STRONG_MATCH_WEIGHT = 0.20
